export const Tasks = [
  {
    id: 0,
    name: 'Реализовать поиск',
    active: true,
    success: false,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-02-04',
    dedline: '14 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 1,
    name: 'Исправить баги',
    active: false,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-01-18',
    dedline: '7 days',
    blocked: false,
    overdue: true,
  },
  {
    id: 2,
    name: 'Добавить авторизацию',
    active: true,
    success: true,
    project: 'E-Commerce Platform',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-10',
    dedline: '21 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 3,
    name: 'Оптимизировать запросы',
    active: false,
    success: false,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-22',
    dedline: '3 days',
    blocked: true,
    overdue: true,
  },
  {
    id: 4,
    name: 'Обновить UI',
    active: true,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-02-01',
    dedline: '10 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 5,
    name: 'Настроить CI/CD',
    active: true,
    success: false,
    project: 'E-Commerce Platform',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-14',
    dedline: '30 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 6,
    name: 'Добавить тесты',
    active: false,
    success: true,
    project: 'Admin Dashboard',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-07',
    dedline: '14 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 7,
    name: 'Исправить стили',
    active: true,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-01-27',
    dedline: '5 days',
    blocked: false,
    overdue: true,
  },
  {
    id: 8,
    name: 'Добавить уведомления',
    active: true,
    success: false,
    project: 'E-Commerce Platform',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-11',
    dedline: '21 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 9,
    name: 'Подготовить релиз',
    active: false,
    success: true,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-19',
    dedline: '7 days',
    blocked: false,
    overdue: true,
  },
];
