import type { ProjectInterface } from '../interfaces/Interfaces';

export const ProjectsData: ProjectInterface[] = [
  {
    id: 1,
    title: 'Landing Page',
    description: 'Сверстать главную страницу сайта',
    status: 'Active',
    priority: 'high',
    due_date: '2024-11-20',
    project_id: 1,
    created_by: 2,
    assigned_to: 4,
    tags: ['верстка', 'ui'],
  },
  {
    id: 2,
    title: 'API Integration',
    description: 'Подключить REST API для пользователей',
    status: 'Active',
    priority: 'medium',
    due_date: '2024-12-05',
    project_id: 1,
    created_by: 1,
    assigned_to: 2,
    tags: ['backend', 'api'],
  },
  {
    id: 3,
    title: 'Admin Dashboard',
    description: 'Разработать функционал поиска по задачам',
    status: 'Active',
    priority: 'medium',
    due_date: '2024-12-31',
    project_id: 2,
    created_by: 1,
    assigned_to: 3,
    tags: ['функционал', 'срочно'],
  },
  {
    id: 4,
    title: 'Auth System',
    description: 'Реализовать авторизацию и регистрацию',
    status: 'Completed',
    priority: 'high',
    due_date: '2024-10-15',
    project_id: 3,
    created_by: 3,
    assigned_to: 1,
    tags: ['auth', 'security'],
  },
  {
    id: 5,
    title: 'Bug Fixes',
    description: 'Исправить критические баги в проде',
    status: 'At Risk',
    priority: 'high',
    due_date: '2024-11-02',
    project_id: 2,
    created_by: 4,
    assigned_to: 2,
    tags: ['bugs', 'hotfix'],
  },
  {
    id: 6,
    title: 'Dark Mode',
    description: 'Добавить темную тему интерфейса',
    status: 'Paused',
    priority: 'low',
    due_date: '2025-01-10',
    project_id: 4,
    created_by: 2,
    assigned_to: 5,
    tags: ['ui', 'ux'],
  },
];
