import type { TaskInterface } from '../interfaces/Interfaces';

export const Tasks: TaskInterface[] = [
  {
    id: 1,
    name: 'Разработка архитектуры базы данных',
    status: 'completed',
    projectId: 1,
    priority: 'high',
    createdAt: '2024-01-15',
    deadline: '20 days',
    tags: ['backend', 'database', 'planning'],
  },
  {
    id: 2,
    name: 'Создание UI компонентов',
    status: 'active',
    projectId: 2,
    priority: 'high',
    createdAt: '2024-02-10T09:30:00Z',
    deadline: '20 days',
    assigneeId: 2,
    tags: ['frontend', 'react', 'ui'],
  },
  {
    id: 3,
    name: 'Тестирование API эндпоинтов',
    status: 'overdue',
    projectId: 3,
    priority: 'medium',
    createdAt: '2024-02-05T14:20:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['testing', 'backend', 'api'],
  },
  {
    id: 4,
    name: 'Интеграция платежной системы',
    status: 'blocked',
    projectId: 4,
    priority: 'high',
    createdAt: '2024-01-20T11:15:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['payments', 'integration', 'security'],
  },
  {
    id: 5,
    name: 'Оптимизация производительности',
    status: 'active',
    projectId: 5,
    priority: 'medium',
    createdAt: '2024-02-12T13:45:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['performance', 'optimization'],
  },
  {
    id: 6,
    name: 'Документация API',
    status: 'active',
    projectId: 6,
    priority: 'low',
    createdAt: '2024-02-08T10:00:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['documentation', 'api'],
  },
  {
    id: 7,
    name: 'Рефакторинг кода',
    status: 'completed',
    projectId: 2,
    priority: 'low',
    createdAt: '2024-01-25T16:20:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['refactoring', 'code-quality'],
  },
  {
    id: 8,
    name: 'Настройка CI/CD pipeline',
    status: 'active',
    projectId: 1,
    priority: 'medium',
    createdAt: '2024-01-30T09:00:00Z',
    deadline: '20 days',
    assigneeId: 0,
    tags: ['devops', 'ci-cd', 'automation'],
  },
  {
    id: 9,
    name: 'Создание мобильной версии',
    status: 'overdue',
    projectId: 3,
    priority: 'high',
    createdAt: '2024-02-01T14:30:00Z',
    deadline: '20 days',
    assigneeId: 4,
    tags: ['mobile', 'responsive', 'frontend'],
  },
  {
    id: 10,
    name: 'Анализ пользовательских логов',
    status: 'completed',
    projectId: 4,
    priority: 'low',
    createdAt: '2024-01-18T11:00:00Z',
    deadline: '20 days',
    assigneeId: 5,
    tags: ['analytics', 'logs', 'monitoring'],
  },
  {
    id: 11,
    name: 'Обновление зависимостей',
    status: 'blocked',
    projectId: 5,
    priority: 'medium',
    createdAt: '2024-02-14T10:45:00Z',
    deadline: '20 days',
    assigneeId: 1,
    tags: ['dependencies', 'security', 'maintenance'],
  },
  {
    id: 12,
    name: 'Написание unit-тестов',
    status: 'overdue',
    projectId: 6,
    priority: 'medium',
    createdAt: '2024-02-03T13:15:00Z',
    deadline: '20 days',
    assigneeId: 2,
    tags: ['testing', 'unit-tests', 'quality'],
  },
  {
    id: 13,
    name: 'Дизайн дашборда аналитики',
    status: 'completed',
    projectId: 2,
    priority: 'high',
    createdAt: '2024-01-22T15:30:00Z',
    deadline: '20 days',
    assigneeId: 3,
    tags: ['design', 'dashboard', 'analytics'],
  },
  {
    id: 14,
    name: 'Миграция данных',
    status: 'overdue',
    projectId: 3,
    priority: 'high',
    createdAt: '2024-01-28T09:45:00Z',
    deadline: '20 days',
    assigneeId: 4,
    tags: ['migration', 'database', 'data'],
  },
  {
    id: 15,
    name: 'Реализация поиска',
    status: 'overdue',
    projectId: 1,
    priority: 'medium',
    createdAt: '2024-02-06T11:20:00Z',
    deadline: '20 days',
    assigneeId: 5,
    tags: ['search', 'features', 'backend'],
  },
  {
    id: 16,
    name: 'Код-ревью',
    status: 'completed',
    projectId: 2,
    priority: 'low',
    createdAt: '2024-02-09T16:00:00Z',
    deadline: '20 days',
    tags: ['code-review', 'quality'],
    // assigneeId намеренно отсутствует
  },
  {
    id: 17,
    name: 'Настройка мониторинга',
    status: 'active',
    projectId: 3,
    priority: 'medium',
    createdAt: '2024-02-11T14:10:00Z',
    deadline: '20 days',
    assigneeId: 1,
    tags: ['monitoring', 'devops', 'observability'],
  },
  {
    id: 18,
    name: 'Создание отчетов',
    status: 'blocked',
    projectId: 4,
    priority: 'low',
    createdAt: '2024-02-07T10:30:00Z',
    deadline: '20 days',
    assigneeId: 2,
    tags: ['reports', 'business', 'export'],
  },
  {
    id: 19,
    name: 'Оптимизация SEO',
    status: 'blocked',
    projectId: 5,
    priority: 'medium',
    createdAt: '2024-02-13T09:15:00Z',
    deadline: '20 days',
    assigneeId: 3,
    tags: ['seo', 'marketing', 'frontend'],
  },
  {
    id: 20,
    name: 'Бэкап базы данных',
    status: 'overdue',
    projectId: 6,
    priority: 'high',
    createdAt: '2024-01-31T23:00:00Z',
    deadline: '20 days',
    assigneeId: 4,
    tags: ['backup', 'database', 'security'],
  },
];
const qwe = [
  {
    id: 0,
    name: 'Реализовать поиск',
    active: true,
    success: false,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-02-04',
    deadline: '14 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 1,
    name: 'Исправить баги',
    active: false,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-01-18',
    deadline: '7 days',
    blocked: false,
    overdue: true,
  },
  {
    id: 2,
    name: 'Добавить авторизацию',
    active: true,
    success: true,
    project: 'E-Commerce Platform',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-10',
    deadline: '21 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 3,
    name: 'Оптимизировать запросы',
    active: false,
    success: false,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-22',
    deadline: '3 days',
    blocked: true,
    overdue: true,
  },
  {
    id: 4,
    name: 'Обновить UI',
    active: true,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-02-01',
    deadline: '10 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 5,
    name: 'Настроить CI/CD',
    active: true,
    success: false,
    project: 'E-Commerce Platform',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-14',
    deadline: '30 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 6,
    name: 'Добавить тесты',
    active: false,
    success: true,
    project: 'Admin Dashboard',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-07',
    deadline: '14 days',
    blocked: false,
    overdue: false,
  },
  {
    id: 7,
    name: 'Исправить стили',
    active: true,
    success: true,
    project: 'Mobile App',
    risk: 'Low Risk',
    riskId: 3,
    createdAt: '2025-01-27',
    deadline: '5 days',
    blocked: false,
    overdue: true,
  },
  {
    id: 8,
    name: 'Добавить уведомления',
    active: true,
    success: false,
    project: 'E-Commerce Platform',
    risk: 'Medium Risk',
    riskId: 2,
    createdAt: '2025-02-11',
    deadline: '21 days',
    blocked: true,
    overdue: false,
  },
  {
    id: 9,
    name: 'Подготовить релиз',
    active: false,
    success: true,
    project: 'Admin Dashboard',
    risk: 'High Risk',
    riskId: 1,
    createdAt: '2025-01-19',
    deadline: '7 days',
    blocked: false,
    overdue: true,
  },
];
