import type { UserInterface } from '../interfaces/Interfaces';

export const mockUsers: UserInterface[] = [
  {
    userid: 0,
    email: 'botoli@gmail.com',
    password: 'passwd',
    name: 'botoli',
    online: false,
    role: 'Admin',
    avatar: false,
  },
  {
    userid: 1,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 2,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 3,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 4,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 5,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 6,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 7,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 8,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 9,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 10,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 11,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 12,
    email: 'bnix@gmail.com',
    password: 'passwd',
    name: 'bnix',
    online: true,
    role: 'Designer',
    avatar: false,
  },
  {
    userid: 13,
    email: 'test@gmail.com',
    password: 'passwd',
    name: 'test',
    online: true,
    role: 'Senior',
    avatar: false,
  },
];
