import type { ProjectInterface } from './Projects.interface';

export const Projects: ProjectInterface[] = [
  {
    id: 0,
    title: 'Mobile App',
    description: 'Создать дизайн и верстку главной страницы',
    status: 'Active',
    priority: 'high',
    due_date: '2024-12-31',
    project_id: 1,
    created_by: 1,
    assigned_to: 2,
    tags: ['дизайн', 'срочно'],
  },
  {
    id: 1,
    title: 'E-Commerce Platform',
    description: 'Разработать функционал поиска по задачам',
    status: 'Active',
    priority: 'medium',
    due_date: '2024-12-31',
    project_id: 2,
    created_by: 1,
    assigned_to: 3,
    tags: ['функционал', 'срочно'],
  },
  {
    id: 2,
    title: 'Admin Dashboard',
    description: 'Разработать функционал поиска по задачам',
    status: 'Active',
    priority: 'medium',
    due_date: '2024-12-31',
    project_id: 2,
    created_by: 1,
    assigned_to: 3,
    tags: ['функционал', 'срочно'],
  },
];
